#!/usr/bin/env bash
# Install and configure Nginx to return a specific content

apt-get update -y
apt-get install -y nginx

echo "Holberton School for the win!" > /var/www/html/index.html

service nginx restart
